config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :create, :new, :edit, :show] do
    resources :reviews, only: [:index, :new, :create ]
  end
  resources :reviews, only: [ :show, :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  CATEGORY = ['chinese', 'italian', 'japanese', 'french', 'belgian'].freeze
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  RATING = [0, 1, 2, 3, 4, 5].freeze
  validates :rating, inclusion: { in: RATING }
  validates :content, presence: true, length: { minimum: 1 }
  validates :rating, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <!-- app/views/layouts/application.html.erb -->
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="navbar-lewagon px-3 py-2">
  <div class="container">
    <div class="row">
      <div class="col-center">
        <div class="nav-flex">
          <h2>My restaurants</h2>
          <%= link_to "+ Add a new restaurant", new_restaurant_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-center">
      <ul class='list-inline pt-5'>
        <% @restaurants.each do |restaurant| %>
        <li><%= restaurant.name.capitalize %>   <%= link_to "Details", restaurant_path(restaurant), class: "bouton btn btn-primary round" %></li>
        <li><%= restaurant.category %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>
<%= form_for(@restaurant) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :address %>
<%= f.text_field :address %>
<%= f.label :category %>
<%= f.select :category, collection: Restaurant::CATEGORY %>
<%= f.label :phone_number %>
<%= f.text_field :phone_number %>
<%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<div class="navbar-lewagon px-3 py-2">
  <div class="container">
    <div class="row">
      <div class="col-center">
        <div class="nav-flex">
          <h1><%= @restaurant.name %></h1>
          <%= link_to 'Leave a review', new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
<%= link_to "Back to list", restaurants_path, class: "btn btn-primary" %>

        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-center">
      <div class="nav-flex">
        <ul class='list-inline pt-5'>
          <li><%= @restaurant.category %></li>
          <li><%= @restaurant.address %></li>
          <li><%= @restaurant.phone_number %></li>
          <!-- ... -->
          <ul class="list-group">
            <% @restaurant.reviews.each do |review| %>
            <li class="list-group-item">
              <%= review.content %>
              <%= '*' * review.rating %>
            </li>
            <% end %>
          </ul>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.select :rating, collection: Review::RATING %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>